[window]
decorations_theme_variant = "None"
opacity = 0.95
padding = { x = 10, y = 10 }
decorations = "Full"
startup_mode = "Maximized"

[font]
normal = { family = "3270 Nerd Font Mono", style = "Regular" }
size = 20 

# Key bindings for font size adjustment
[keyboard]
bindings = [
  { key = "Equals", mods = "Command", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Command", action = "DecreaseFontSize" }
]

